In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [0]:
data = np.random.randint(0, 100, (10, 2))

In [5]:
data

array([[52, 56],
       [13, 59],
       [63, 87],
       [ 0, 30],
       [71, 23],
       [18, 84],
       [33, 47],
       [62, 26],
       [55, 65],
       [82, 41]])

In [0]:
scaler_model = MinMaxScaler()

In [7]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.63414634, 0.515625  ],
       [0.15853659, 0.5625    ],
       [0.76829268, 1.        ],
       [0.        , 0.109375  ],
       [0.86585366, 0.        ],
       [0.2195122 , 0.953125  ],
       [0.40243902, 0.375     ],
       [0.75609756, 0.046875  ],
       [0.67073171, 0.65625   ],
       [1.        , 0.28125   ]])

In [9]:
scaler_model.fit_transform(data)

array([[0.63414634, 0.515625  ],
       [0.15853659, 0.5625    ],
       [0.76829268, 1.        ],
       [0.        , 0.109375  ],
       [0.86585366, 0.        ],
       [0.2195122 , 0.953125  ],
       [0.40243902, 0.375     ],
       [0.75609756, 0.046875  ],
       [0.67073171, 0.65625   ],
       [1.        , 0.28125   ]])

In [0]:
import pandas as pd

In [0]:
data = np.random.randint(0, 101, (50, 4))

In [12]:
data

array([[ 49,  90,   5,  72],
       [ 57,  45,  86,  82],
       [ 71,  33,   9,  54],
       [ 32, 100,  46,  64],
       [ 77,  47,  42,  24],
       [ 83,  14,  12,  80],
       [ 44,  72,   2,  38],
       [ 51,   7,   9,  41],
       [ 86,  55,  55,  32],
       [ 31,  88,  27,  98],
       [ 64,   2,  32,  66],
       [  2,  33,  66,  69],
       [ 51,   7,  64,  58],
       [ 72,  80,  85,  95],
       [ 17,  85,  60,  42],
       [ 22,  86,  46,   6],
       [ 87,  56,  94,  14],
       [ 46,  19,  78,  78],
       [ 12,  11,  36,  11],
       [ 39,  43,  19,  39],
       [ 46,   1,  79,  54],
       [ 41,  91,  61,  52],
       [ 19,  68,  88,  72],
       [ 43,  17,  13,  43],
       [ 69,  51,  27,  83],
       [ 32,  77,  31,  13],
       [ 30,  95,  99,  59],
       [ 33,  47,  58,  72],
       [ 23,  67,   5,  54],
       [ 38,  12,  57,  92],
       [ 25,  71,   2,   8],
       [ 44,  83,   2,  54],
       [ 99,  79,  69,  13],
       [ 94,  29,  40, 100],
       [  5,  

In [0]:
df = pd.DataFrame(data = data, columns = ['f1', 'f2', 'f3', 'label'])

In [20]:
df

f1   f2   f3  label
0   49   90    5     72
1   57   45   86     82
2   71   33    9     54
3   32  100   46     64
4   77   47   42     24
5   83   14   12     80
6   44   72    2     38
7   51    7    9     41
8   86   55   55     32
9   31   88   27     98
10  64    2   32     66
11   2   33   66     69
12  51    7   64     58
13  72   80   85     95
14  17   85   60     42
15  22   86   46      6
16  87   56   94     14
17  46   19   78     78
18  12   11   36     11
19  39   43   19     39
20  46    1   79     54
21  41   91   61     52
22  19   68   88     72
23  43   17   13     43
24  69   51   27     83
25  32   77   31     13
26  30   95   99     59
27  33   47   58     72
28  23   67    5     54
29  38   12   57     92
30  25   71    2      8
31  44   83    2     54
32  99   79   69     13
33  94   29   40    100
34   5   52   52     88
35  91   96   69      1
36  12    8   68     68
37  99    5   28     35
38  36   73   10     70
39  84   63   32     55
40  52   20    6     91
41  27   18    8     92
42  87   61   66     99
43  23   90   20      4
44  22   74   76     34
45  62   64   76     47
46  75    2   26      7
47   4   87  100     60
48  59    3   34      2
49   2   20   72     32

In [0]:
X = df[['f1', 'f2', 'f3']]

In [0]:
Y = df[['label']]

In [26]:
X

f1   f2   f3
0   49   90    5
1   57   45   86
2   71   33    9
3   32  100   46
4   77   47   42
5   83   14   12
6   44   72    2
7   51    7    9
8   86   55   55
9   31   88   27
10  64    2   32
11   2   33   66
12  51    7   64
13  72   80   85
14  17   85   60
15  22   86   46
16  87   56   94
17  46   19   78
18  12   11   36
19  39   43   19
20  46    1   79
21  41   91   61
22  19   68   88
23  43   17   13
24  69   51   27
25  32   77   31
26  30   95   99
27  33   47   58
28  23   67    5
29  38   12   57
30  25   71    2
31  44   83    2
32  99   79   69
33  94   29   40
34   5   52   52
35  91   96   69
36  12    8   68
37  99    5   28
38  36   73   10
39  84   63   32
40  52   20    6
41  27   18    8
42  87   61   66
43  23   90   20
44  22   74   76
45  62   64   76
46  75    2   26
47   4   87  100
48  59    3   34
49   2   20   72

In [27]:
Y

label
0      72
1      82
2      54
3      64
4      24
5      80
6      38
7      41
8      32
9      98
10     66
11     69
12     58
13     95
14     42
15      6
16     14
17     78
18     11
19     39
20     54
21     52
22     72
23     43
24     83
25     13
26     59
27     72
28     54
29     92
30      8
31     54
32     13
33    100
34     88
35      1
36     68
37     35
38     70
39     55
40     91
41     92
42     99
43      4
44     34
45     47
46      7
47     60
48      2
49     32

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 101)

In [31]:
X_train.shape

(35, 3)

In [32]:
X_test.shape

(15, 3)