# TF BASIC SYNTAX

In [0]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [0]:
hello = tf.constant("Hello ")

In [0]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello + world)

In [8]:
print(result)

b'Hello World'


In [0]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result = sess.run(a + b)

In [14]:
result

30

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4, 4), 10)

In [0]:
myzeros = tf.zeros((4, 4))

In [0]:
myones = tf.ones((4, 4))

In [0]:
myrandn = tf.random_normal((4, 4))

In [0]:
myrandu = tf.random_uniform((4, 4))

In [0]:
myops = [const, fill_mat, myones, myzeros, myrandn, myrandu]

In [0]:
sess = tf.InteractiveSession()

In [29]:
for op in myops:
  print(sess.run(op))
  print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.5206725   0.07502091  0.12990369  0.46660414]
 [-0.0788477  -0.02218497  1.0783424   0.7892011 ]
 [-1.2604939  -1.3405076   0.03514453 -0.5143865 ]
 [ 0.20295313  1.4763072  -0.44865003 -0.18580118]]


[[0.15164125 0.13092828 0.16356838 0.32934546]
 [0.2379787  0.45534396 0.7636224  0.06934595]
 [0.530534   0.82694864 0.979326   0.18134868]
 [0.84700644 0.72637725 0.5759065  0.9722582 ]]




In [30]:
a = tf.constant([[1, 2],
                 [3, 4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([[10], [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a, b)
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [33]:
result.eval()

array([[210],
       [430]], dtype=int32)